// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { NextApiHandler, ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}

type ApiRouteConfig = {
  default: (req: any, res: any) => ReturnType<NextApiHandler>
  config?: {
    api?: {
      bodyParser?: boolean | { sizeLimit?: string }
      responseLimit?: string | number | boolean
      externalResolver?: boolean
    }
    runtime?: 'edge' | 'experimental-edge' | 'nodejs' | string // necessary unless config is exported as const
    maxDuration?: number
  }
}


// Validate ../../app/(store)/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../app/(store)/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(store)/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cart">> = Specific
  const handler = {} as typeof import("../../app/(store)/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(store)/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../app/(store)/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(store)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(store)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(store)/product/[sku]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product/[sku]">> = Specific
  const handler = {} as typeof import("../../app/(store)/product/[sku]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/audit">> = Specific
  const handler = {} as typeof import("../../app/admin/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/companies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/companies">> = Specific
  const handler = {} as typeof import("../../app/admin/companies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/completeness/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/completeness">> = Specific
  const handler = {} as typeof import("../../app/admin/completeness/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/crm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/crm">> = Specific
  const handler = {} as typeof import("../../app/admin/crm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/customers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/customers/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/customers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/customers">> = Specific
  const handler = {} as typeof import("../../app/admin/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../app/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/flags/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/flags">> = Specific
  const handler = {} as typeof import("../../app/admin/flags/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/integrations/[provider]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/integrations/[provider]">> = Specific
  const handler = {} as typeof import("../../app/admin/integrations/[provider]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/integrations/multicase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/integrations/multicase">> = Specific
  const handler = {} as typeof import("../../app/admin/integrations/multicase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/integrations/omnium/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/integrations/omnium">> = Specific
  const handler = {} as typeof import("../../app/admin/integrations/omnium/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/integrations">> = Specific
  const handler = {} as typeof import("../../app/admin/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/integrations/rackbeat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/integrations/rackbeat">> = Specific
  const handler = {} as typeof import("../../app/admin/integrations/rackbeat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/integrations/salesforce/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/integrations/salesforce">> = Specific
  const handler = {} as typeof import("../../app/admin/integrations/salesforce/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/inventory">> = Specific
  const handler = {} as typeof import("../../app/admin/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/jobs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/jobs">> = Specific
  const handler = {} as typeof import("../../app/admin/jobs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/magento/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/magento">> = Specific
  const handler = {} as typeof import("../../app/admin/magento/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/orders/[id]/fulfillment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders/[id]/fulfillment">> = Specific
  const handler = {} as typeof import("../../app/admin/orders/[id]/fulfillment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/orders/[id]/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders/[id]/payments">> = Specific
  const handler = {} as typeof import("../../app/admin/orders/[id]/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/orders/[id]/returns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders/[id]/returns">> = Specific
  const handler = {} as typeof import("../../app/admin/orders/[id]/returns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/orders/kanban/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders/kanban">> = Specific
  const handler = {} as typeof import("../../app/admin/orders/kanban/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/orders/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders/new">> = Specific
  const handler = {} as typeof import("../../app/admin/orders/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders">> = Specific
  const handler = {} as typeof import("../../app/admin/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/orders/sync/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders/sync">> = Specific
  const handler = {} as typeof import("../../app/admin/orders/sync/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/pricing/campaigns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pricing/campaigns">> = Specific
  const handler = {} as typeof import("../../app/admin/pricing/campaigns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pricing">> = Specific
  const handler = {} as typeof import("../../app/admin/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/pricing/pricelists/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pricing/pricelists">> = Specific
  const handler = {} as typeof import("../../app/admin/pricing/pricelists/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/products/[sku]/advanced/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products/[sku]/advanced">> = Specific
  const handler = {} as typeof import("../../app/admin/products/[sku]/advanced/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/products/[sku]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products/[sku]">> = Specific
  const handler = {} as typeof import("../../app/admin/products/[sku]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/products/feeds/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products/feeds">> = Specific
  const handler = {} as typeof import("../../app/admin/products/feeds/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/products/grid/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products/grid">> = Specific
  const handler = {} as typeof import("../../app/admin/products/grid/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/products/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products/new">> = Specific
  const handler = {} as typeof import("../../app/admin/products/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/products/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products/overview">> = Specific
  const handler = {} as typeof import("../../app/admin/products/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products">> = Specific
  const handler = {} as typeof import("../../app/admin/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/purchasing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/purchasing">> = Specific
  const handler = {} as typeof import("../../app/admin/purchasing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/returns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/returns">> = Specific
  const handler = {} as typeof import("../../app/admin/returns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/settings/order-flows/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/order-flows">> = Specific
  const handler = {} as typeof import("../../app/admin/settings/order-flows/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/product/[sku]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product/[sku]">> = Specific
  const handler = {} as typeof import("../../app/product/[sku]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/store/product/[sku]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/store/product/[sku]">> = Specific
  const handler = {} as typeof import("../../app/store/product/[sku]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/audit">> = Specific
  const handler = {} as typeof import("../../app/api/admin/audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/feed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/feed">> = Specific
  const handler = {} as typeof import("../../app/api/admin/feed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/flags/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/flags">> = Specific
  const handler = {} as typeof import("../../app/api/admin/flags/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/kpis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/kpis">> = Specific
  const handler = {} as typeof import("../../app/api/admin/kpis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/orders/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/orders/bulk">> = Specific
  const handler = {} as typeof import("../../app/api/admin/orders/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/orders">> = Specific
  const handler = {} as typeof import("../../app/api/admin/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/orders/seed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/orders/seed">> = Specific
  const handler = {} as typeof import("../../app/api/admin/orders/seed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/reco/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/reco">> = Specific
  const handler = {} as typeof import("../../app/api/ai/reco/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/akeneo/attributes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/akeneo/attributes">> = Specific
  const handler = {} as typeof import("../../app/api/akeneo/attributes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/akeneo/channels/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/akeneo/channels">> = Specific
  const handler = {} as typeof import("../../app/api/akeneo/channels/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/akeneo/families/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/akeneo/families">> = Specific
  const handler = {} as typeof import("../../app/api/akeneo/families/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audit/products/[sku]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/products/[sku]">> = Specific
  const handler = {} as typeof import("../../app/api/audit/products/[sku]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit">> = Specific
  const handler = {} as typeof import("../../app/api/audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/role/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/role">> = Specific
  const handler = {} as typeof import("../../app/api/auth/role/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/catalog/product/[sku]/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/catalog/product/[sku]/config">> = Specific
  const handler = {} as typeof import("../../app/api/catalog/product/[sku]/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/catalog/product/[sku]/lots/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/catalog/product/[sku]/lots">> = Specific
  const handler = {} as typeof import("../../app/api/catalog/product/[sku]/lots/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/catalog/product/[sku]/variants/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/catalog/product/[sku]/variants">> = Specific
  const handler = {} as typeof import("../../app/api/catalog/product/[sku]/variants/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/catalog/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/catalog/products">> = Specific
  const handler = {} as typeof import("../../app/api/catalog/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/catalog/variants/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/catalog/variants">> = Specific
  const handler = {} as typeof import("../../app/api/catalog/variants/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/companies/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/companies/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/companies/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/companies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/companies">> = Specific
  const handler = {} as typeof import("../../app/api/companies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/crm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crm">> = Specific
  const handler = {} as typeof import("../../app/api/crm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/customers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customers/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/customers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/customers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customers">> = Specific
  const handler = {} as typeof import("../../app/api/customers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/customers/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customers/sync">> = Specific
  const handler = {} as typeof import("../../app/api/customers/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/debug/env/magento/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/env/magento">> = Specific
  const handler = {} as typeof import("../../app/api/debug/env/magento/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/debug/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/health">> = Specific
  const handler = {} as typeof import("../../app/api/debug/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/env/auth-check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/env/auth-check">> = Specific
  const handler = {} as typeof import("../../app/api/env/auth-check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/env/check-loader/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/env/check-loader">> = Specific
  const handler = {} as typeof import("../../app/api/env/check-loader/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/env/check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/env/check">> = Specific
  const handler = {} as typeof import("../../app/api/env/check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/env/cleanup-authcheck/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/env/cleanup-authcheck">> = Specific
  const handler = {} as typeof import("../../app/api/env/cleanup-authcheck/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/flags/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/flags">> = Specific
  const handler = {} as typeof import("../../app/api/flags/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/health">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/inventory/allocate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/allocate">> = Specific
  const handler = {} as typeof import("../../app/api/inventory/allocate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/inventory/consume/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/consume">> = Specific
  const handler = {} as typeof import("../../app/api/inventory/consume/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/jobs/latest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/latest">> = Specific
  const handler = {} as typeof import("../../app/api/jobs/latest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/jobs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs">> = Specific
  const handler = {} as typeof import("../../app/api/jobs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/jobs/run-sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/run-sync">> = Specific
  const handler = {} as typeof import("../../app/api/jobs/run-sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/magento/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/magento/health">> = Specific
  const handler = {} as typeof import("../../app/api/magento/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/magento/sync/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/magento/sync/orders">> = Specific
  const handler = {} as typeof import("../../app/api/magento/sync/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/magento/sync/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/magento/sync/products">> = Specific
  const handler = {} as typeof import("../../app/api/magento/sync/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/[id]/returns/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/returns">> = Specific
  const handler = {} as typeof import("../../app/api/orders/[id]/returns/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/orders/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders">> = Specific
  const handler = {} as typeof import("../../app/api/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/sync">> = Specific
  const handler = {} as typeof import("../../app/api/orders/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pricing/campaigns/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing/campaigns">> = Specific
  const handler = {} as typeof import("../../app/api/pricing/campaigns/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pricing/effective/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing/effective">> = Specific
  const handler = {} as typeof import("../../app/api/pricing/effective/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pricing/pricelists/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing/pricelists">> = Specific
  const handler = {} as typeof import("../../app/api/pricing/pricelists/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pricing/quote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing/quote">> = Specific
  const handler = {} as typeof import("../../app/api/pricing/quote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pricing/rules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing/rules">> = Specific
  const handler = {} as typeof import("../../app/api/pricing/rules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/product-meta/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/product-meta/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/product-meta/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/[sku]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[sku]">> = Specific
  const handler = {} as typeof import("../../app/api/products/[sku]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/attributes/[sku]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/attributes/[sku]">> = Specific
  const handler = {} as typeof import("../../app/api/products/attributes/[sku]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/attributes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/attributes">> = Specific
  const handler = {} as typeof import("../../app/api/products/attributes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/bulk">> = Specific
  const handler = {} as typeof import("../../app/api/products/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/completeness/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/completeness">> = Specific
  const handler = {} as typeof import("../../app/api/products/completeness/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/export">> = Specific
  const handler = {} as typeof import("../../app/api/products/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/import">> = Specific
  const handler = {} as typeof import("../../app/api/products/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/merged/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/merged">> = Specific
  const handler = {} as typeof import("../../app/api/products/merged/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products">> = Specific
  const handler = {} as typeof import("../../app/api/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/seed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/seed">> = Specific
  const handler = {} as typeof import("../../app/api/products/seed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/sync">> = Specific
  const handler = {} as typeof import("../../app/api/products/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/update-attributes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/update-attributes">> = Specific
  const handler = {} as typeof import("../../app/api/products/update-attributes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/update-family/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/update-family">> = Specific
  const handler = {} as typeof import("../../app/api/products/update-family/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/returns/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/returns">> = Specific
  const handler = {} as typeof import("../../app/api/returns/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rules">> = Specific
  const handler = {} as typeof import("../../app/api/rules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sync/magento/product/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync/magento/product/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/sync/magento/product/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users">> = Specific
  const handler = {} as typeof import("../../app/api/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}



// Validate ../../pages/api/_debug/env.ts
{
  type __IsExpected<Specific extends ApiRouteConfig> = Specific
  const handler = {} as typeof import("../../pages/api/_debug/env.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../pages/api/_debug/ping.ts
{
  type __IsExpected<Specific extends ApiRouteConfig> = Specific
  const handler = {} as typeof import("../../pages/api/_debug/ping.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(store)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(store)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/products/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin/products">> = Specific
  const handler = {} as typeof import("../../app/admin/products/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
